name: Node.js CI

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: corepack enable 
      - run: corepack prepare pnpm@latest-8 --activate 
      - run: pnpm config set store-dir .pnpm-store
      - run: pnpm install
      - run: pnpm lint:ci
      - run: pnpm build
